# Generated by Django 5.2 on 2025-04-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiants.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("matricule", models.CharField(max_length=20, unique=True)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                ("inscrit", models.BooleanField(default=False)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiants.departement",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiants.filiere",
                    ),
                ),
            ],
        ),
    ]
