# Generated by Django 5.2 on 2025-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="inscrit",
            field=models.BooleanField(default=False),
        ),
    ]
