# Generated by Django 5.2 on 2025-04-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departement",
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
            },
        ),
        migrations.AlterModelOptions(
            name="etudiant",
            options={"verbose_name": "Étudiant", "verbose_name_plural": "Étudiants"},
        ),
        migrations.AlterModelOptions(
            name="filiere",
            options={"verbose_name": "Filière", "verbose_name_plural": "Filières"},
        ),
    ]
